Moneyer/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(pattern_name='to_get_back_money:to-get-back-list', permanent=False)),

    path('to_get_back/', include('to_get_back_money.urls')),

    path('to_return/', include('to_return_money.urls')),
]

to_get_back_money/urls.py
from django.urls import path
from to_get_back_money.views import GetBackListView, GetBackCreateView, GetBackDetailView, GetBackDeleteView, GetBackUpdateView

app_name = 'to_get_back_money'
urlpatterns = [
    path('', GetBackListView.as_view(), name='to-get-back-list'),
    path('create', GetBackCreateView.as_view(), name='to-get-back-create'),
    path('<int:id>', GetBackDetailView.as_view(), name='to-get-back-details'),
    path('delete/<int:id>', GetBackDeleteView.as_view(), name='to-get-back-delete'),
    path('update/<int:pk>', GetBackUpdateView.as_view(), name='to-get-back-update'),
]

to_return_money/urls.py
from django.urls import path
from to_return_money.views import ReturnListView, ReturnCreateView, ReturnDetailView, ReturnDeleteView, ReturnUpdateView


app_name = "to_return_money"
urlpatterns = [
    path('', ReturnListView.as_view(), name='to-return-list'),
    path('create', ReturnCreateView.as_view(), name='to-return-create'),
    path('<int:id>', ReturnDetailView.as_view(), name='to-return-details'),
    path('delete/<int:id>', ReturnDeleteView.as_view(), name='to-return-delete'),
    path('update/<int:pk>', ReturnUpdateView.as_view(), name='to-return-update'),
]

to_get_back_money/models.py
from decimal import Decimal

from django.core.validators import MinValueValidator
from django.db import models

# Create your models here.
from django.urls import reverse


class GetBackMoney(models.Model):
    title = models.CharField(max_length=25)
    amount = models.DecimalField(max_digits=5,decimal_places=2, validators=[MinValueValidator(Decimal('0.01'))])
    short_description = models.CharField(max_length=100)

    def get_absolute_url(self):
        return reverse("to_get_back_money:to-get-back-details",kwargs={"id":self.id})

to_return_money/models.py
from decimal import Decimal

from django.core.validators import MinValueValidator
from django.db import models

# Create your models here.
from django.urls import reverse


class ReturnMoney(models.Model):
    title = models.CharField(max_length=25)
    amount = models.DecimalField(max_digits=5,decimal_places=2, validators=[MinValueValidator(Decimal('0.01'))])
    short_description = models.CharField(max_length=100)

    def get_absolute_url(self):
        return reverse("to_return_money:to-return-details",kwargs={"id":self.id})

to_get_back_money/forms.py
from django import forms
from .models import GetBackMoney

class GetBackModelForm(forms.ModelForm):
    class Meta:
        model = GetBackMoney
        fields = ["title",
                  "amount",
                  "short_description"]

        widgets={
            'title': forms.TextInput(attrs={'class':'form-title'}),
            'amount': forms.NumberInput(attrs={'class':'form-amount'}),
            'short_description': forms.TextInput(attrs={'class':'form-description'})
        }

to_return_money/forms.py
from django import forms
from .models import ReturnMoney

class ReturnModelForm(forms.ModelForm):
    class Meta:
        model = ReturnMoney
        fields = ["title",
                  "amount",
                  "short_description"]

        widgets={
            'title': forms.TextInput(attrs={'class':'form-title'}),
            'amount': forms.NumberInput(attrs={'class':'form-amount'}),
            'short_description': forms.TextInput(attrs={'class':'form-description'})
        }

to_get_back_money/views.py
from django.shortcuts import get_object_or_404
from .models import GetBackMoney
from .forms import GetBackModelForm
from django.views.generic import (
    ListView,
    CreateView,
    DetailView,
    DeleteView, UpdateView
)

class GetBackListView(ListView):
    model = GetBackMoney
    template_name = "to_get_back_money/to_get_back.html"

class GetBackDetailView(DetailView):
    template_name = "to_get_back_money/details_to_get_back.html"
    queryset = GetBackMoney.objects.all()

    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(GetBackMoney, id=id_)

class GetBackDeleteView(DeleteView):
    template_name = "to_get_back_money/details_to_get_back.html"
    queryset = GetBackMoney.objects.all()
    success_url = "/to_get_back/"

    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(GetBackMoney, id=id_)

class GetBackCreateView(CreateView):
    template_name = 'create.html'
    form_class = GetBackModelForm
    success_url = '/to_get_back/'
    queryset = GetBackMoney.objects.all()

class GetBackUpdateView(UpdateView):
    template_name = "update.html"
    form_class = GetBackModelForm
    model = GetBackMoney

to_return_money/views.py
from django.shortcuts import  get_object_or_404
from .models import ReturnMoney
from .forms import ReturnModelForm
from django.views.generic import (
    ListView,
    CreateView,
    DetailView,
    DeleteView, UpdateView
)

class ReturnListView(ListView):
    model = ReturnMoney
    template_name = "to_return_money/to_return.html"

class ReturnDetailView(DetailView):
    template_name = "to_return_money/details_to_return.html"
    queryset = ReturnMoney.objects.all()

    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(ReturnMoney, id=id_)

class ReturnDeleteView(DeleteView):
    template_name = "to_return_money/details_to_return.html"
    queryset = ReturnMoney.objects.all()
    success_url = "/to_return/"

    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(ReturnMoney, id=id_)

class ReturnCreateView(CreateView):
    template_name = 'create.html'
    form_class = ReturnModelForm
    success_url = '/to_return/'
    queryset = ReturnMoney.objects.all()

class ReturnUpdateView(UpdateView):
    template_name = "update.html"
    form_class = ReturnModelForm
    model = ReturnMoney

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Moneyer</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Flex:opsz,wght@8..144,300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Zen+Maru+Gothic:wght@300&display=swap" rel="stylesheet">
</head>
<body>
<br>
<br>
    <div class="titlebar glass">
        <a href="{% url 'to_get_back_money:to-get-back-list' %}"><h1>Moneyer</h1></a>
    </div>
    {% block content %}
    {% endblock %}
</body>
</html>

templates/create.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <link rel="stylesheet" href="{% static 'css/create.css' %}">
    <br>
        <form method="post">{% csrf_token %}
            <div class="container glass">
                <div class="">
                    <br>
                <p class="label">Title</p>
                <p>{{ form.title }}</p>
                    <p class="label">Amount</p>
                <p>{{ form.amount }} zł</p>
                    <p class="label">Description</p>
                <p>{{ form.short_description }}</p>
                    <div id="actions">
                        <input id="add-item" type="submit" value="Add">
                    </div>
                </div>{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <p> {{ error }} </p>
        {% endfor %}
    {% endfor %}
{% endif %}
            </div>
        </form>
{% endblock %}

templates/details.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <link rel="stylesheet" href="{% static 'css/details.css' %}">
    <br>
    <div class="header glass">
        <p id="title">{{ object.title }}</p>
        <hr>
        <p id="amount">{{ object.amount }}</p>
        <hr>
        <p id="description">{{ object.short_description }}</p>
    </div>
    <br>
    <div class="actions glass">
            <form action="{% url 'to-get-back-update' object.id %}" method="GET">
                {% csrf_token %}
                <input id="update-button" type="submit" value="Update"/>
            </form>
            <form action="{% url 'to-get-back-delete' object.id %}" method="POST">
                {% csrf_token %}
                <input id="delete-button" type="submit" value="Delete"/>
            </form>
    </div>
    <br>

{% endblock %}

templates/details_to_get_back.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <link rel="stylesheet" href="{% static 'css/details.css' %}">
    <br>
    <div class="header glass">
        <p id="title">{{ object.title }}</p>
        <hr>
        <p id="amount">{{ object.amount }}zł</p>
        <hr>
        <p id="description">{{ object.short_description }}</p>
    </div>
    <br>
    <div class="actions glass">
            <form action="{% url 'to-get-back-update' object.id %}" method="GET">
                {% csrf_token %}
                <input id="update-button" type="submit" value="Update"/>
            </form>
            <form action="{% url 'to-get-back-delete' object.id %}" method="POST">
                {% csrf_token %}
                <input id="delete-button" type="submit" value="Delete"/>
            </form>
    </div>
    <br>

{% endblock %}

templates/details_to_return.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <link rel="stylesheet" href="{% static 'css/details.css' %}">
    <br>
    <div class="header glass">
        <p id="title">{{ object.title }}</p>
        <hr>
        <p id="amount">{{ object.amount }}zł</p>
        <hr>
        <p id="description">{{ object.short_description }}</p>
    </div>
    <br>
    <div class="actions glass">
            <form action="{% url 'to-return-update' object.id %}" method="GET">
                {% csrf_token %}
                <input id="update-button" type="submit" value="Update"/>
            </form>
            <form action="{% url 'to-return-delete' object.id %}" method="POST">
                {% csrf_token %}
                <input id="delete-button" type="submit" value="Delete"/>
            </form>
    </div>
    <br>

{% endblock %}

templates/navbar.html
<div class="navbar-glass">
        <a href="/to_get_back/"><span id="to-get-back">To get back</span></a>
        <a href="/to_return/"><span id="to-return">To return</span></a>
</div>

templates/to_get_back.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <link rel="stylesheet" href="{% static 'css/to_get_back.css' %}">
    <br>
    {% include "navbar.html" %}
    <div id="add"><a href="{% url 'to-get-back-create' %}">+</a></div>
    <div class="money-table glass">
        <ul>
            {% for instance in object_list %}
                <li><a href="{% url 'to-get-back-details' instance.id %}">{{ instance.title }} - {{ instance.amount }}zł<br><span id="short-description">{{ instance.short_description }}</span></a></li>
                <hr>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

templates/to_return.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <link rel="stylesheet" href="{% static 'css/to_return.css' %}">
    <br>
    {% include "navbar.html" %}
    <div id="add"><a href="{% url 'to-return-create' %}">+</a></div>
    <div class="money-table glass">
        <ul>
            {% for instance in object_list %}
                <li><a href="{% url 'to-return-details' instance.id %}">{{ instance.title }} - {{ instance.amount }}zł<br><span id="short-description">{{ instance.short_description }}</span></a></li>
                <hr>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

templates/update.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <link rel="stylesheet" href="{% static 'css/update.css' %}">
    <br>
        <form method="post">{% csrf_token %}
            <div class="container glass">
                <div class="">
                    <br>
                <p class="label">Title</p>
                <p>{{ form.title }}</p>
                    <p class="label">Amount</p>
                <p>{{ form.amount }}</p>
                    <p class="label">Description</p>
                <p>{{ form.short_description }}</p>
                    <div id="actions">
                        <input id="update-item" type="submit" value="Update">
                    </div>
                </div>{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <p> {{ error }} </p>
        {% endfor %}
    {% endfor %}
{% endif %}
            </div>
        </form>
{% endblock %}

templates/update_to_get_back.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <link rel="stylesheet" href="{% static 'css/update_to_get_back.css' %}">
    <br>
        <form method="post">{% csrf_token %}
            <div class="container glass">
                <div class="">
                    <br>
                <p class="label">Title</p>
                <p>{{ form.title }}</p>
                    <p class="label">Amount</p>
                <p>{{ form.amount }}</p>
                    <p class="label">Description</p>
                <p>{{ form.short_description }}</p>
                    <div id="actions">
                        <input id="update-item" type="submit" value="Update">
                    </div>
                </div>{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <p> {{ error }} </p>
        {% endfor %}
    {% endfor %}
{% endif %}
            </div>
        </form>
{% endblock %}

templates/update_to_return.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <link rel="stylesheet" href="{% static 'css/update_to_get_back.css' %}">
    <br>
        <form method="post">{% csrf_token %}
            <div class="container glass">
                <div class="">
                    <br>
                <p class="label">Title</p>
                <p>{{ form.title }}</p>
                    <p class="label">Amount</p>
                <p>{{ form.amount }}</p>
                    <p class="label">Description</p>
                <p>{{ form.short_description }}</p>
                    <div id="actions">
                        <input id="update-item" type="submit" value="Update">
                    </div>
                </div>{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <p> {{ error }} </p>
        {% endfor %}
    {% endfor %}
{% endif %}
            </div>
        </form>
{% endblock %}

to_get_back_money/templates/to_get_back_money/details_to_get_back.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <link rel="stylesheet" href="{% static 'css/details.css' %}">
    <br>
    <div class="header glass">
        <p id="title">{{ object.title }}</p>
        <hr>
        <p id="amount">{{ object.amount }}zł</p>
        <hr>
        <p id="description">{{ object.short_description }}</p>
    </div>
    <br>
    <div class="actions glass">
            <form action="{% url 'to_get_back_money:to-get-back-update' object.id %}" method="GET">
                <input id="update-button" type="submit" value="Update"/>
            </form>
            <form action="{% url 'to_get_back_money:to-get-back-delete' object.id %}" method="POST">
                {% csrf_token %}
                <input id="delete-button" type="submit" value="Delete"/>
            </form>
    </div>
    <br>

{% endblock %}

to_get_back_money/templates/to_get_back_money/to_get_back.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <link rel="stylesheet" href="{% static 'css/to_get_back.css' %}">
    <br>
    {% include "navbar.html" %}
    <div id="add"><a href="{% url 'to_get_back_money:to-get-back-create' %}">+</a></div>
    <div class="money-table glass">
        <ul>
            {% for instance in object_list %}
                <li><a href="{% url 'to_get_back_money:to-get-back-details' instance.id %}">{{ instance.title }} - {{ instance.amount }}zł<br><span id="short-description">{{ instance.short_description }}</span></a></li>
                <hr>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

to_return_money/templates/to_return_money/details_to_return.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <link rel="stylesheet" href="{% static 'css/details.css' %}">
    <br>
    <div class="header glass">
        <p id="title">{{ object.title }}</p>
        <hr>
        <p id="amount">{{ object.amount }}zł</p>
        <hr>
        <p id="description">{{ object.short_description }}</p>
    </div>
    <br>
    <div class="actions glass">
            <form action="{% url 'to_return_money:to-return-update' object.id %}" method="GET">
                <input id="update-button" type="submit" value="Update"/>
            </form>
            <form action="{% url 'to_return_money:to-return-delete' object.id %}" method="POST">
                {% csrf_token %}
                <input id="delete-button" type="submit" value="Delete"/>
            </form>
    </div>
    <br>

{% endblock %}

to_return_money/templates/to_return_money/to_return.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <link rel="stylesheet" href="{% static 'css/to_return.css' %}">
    <br>
    {% include "navbar.html" %}
    <div id="add"><a href="{% url 'to_return_money:to-return-create' %}">+</a></div>
    <div class="money-table glass">
        <ul>
            {% for instance in object_list %}
                <li><a href="{% url 'to_return_money:to-return-details' instance.id %}">{{ instance.title }} - {{ instance.amount }}zł<br><span id="short-description">{{ instance.short_description }}</span></a></li>
                <hr>
            {% endfor %}
        </ul>
    </div>
{% endblock %}